title: Tito Spadini
description: Engenheiro de Informação, Cientista, Pesquisador e Divulgador Científico
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
timezone: America/Sao_Paulo

url:  https://titocaco.github.io
languages: "Portuguese"
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: "Portuguese"

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
