title: Tito Spadini
description: Information Engineer & Scientist
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

url:  https://titocaco.github.io
languages: ["en", "pt"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  en: English
  pt: Portuguese

gems:
  - jekyll-multiple-languages-plugin