title: Tito Spadini
description: Information Engineer, Scientist, Researcher, Professor, Investor, Developer, Musician, Writer and Gamer.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman